FROM python:3.6
MAINTAINER thanhnb "bathanhtlu@gmail.com"

RUN apt-get update && apt-get -y install build-essential \
libssl-dev libffi-dev python-dev \
libsasl2-dev python-dev libldap2-dev \
libssl-dev

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements/dev2.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt
